### ISSUE TITLE
Estimated amount of work for decoder handling of chunked data

### ISSUE THREAD

**Issue by tangram67** [Harinlen/GPUraku#1]
Hi.

This is not really an issue, more a question....

I took a first glance through the code an I noticed that the whole FLAC source file is mapped into memory. My question is: Is it possible to use an update() call procedure where the FLAC data is delivered in small pieces and the decoded data is stored in dedicated buffers? 

I'm asking this question because I'm not really experienced in CUDA programming. I just want to know if that looks possible from you point of view? Or will that take a major rewrite of some essential parts of the CUDA decoder methods when the data is separated into chunks and the CUDA processes has to be started again for each data chunk?

Regards,
Dirk.

**Comment by Harinlen** [comment]
Hi Dirk,

Thanks for your question.

The way you mentioned is more like the way working of a software decoder or a hardware decoding DSP. Here what I did is to use as many cores as the GPU has to find and decode all the frames (the piece you mentioned) concurrently. CUDA cores on NVIDIA GPUs are grouped in different scale (Kepler is 192, Maxwell and Pascal are 32, Turing breaks it into 32 ALUs and FP32 Units) before GTX 10 series, which means CUDA cores are hard (I believe it is impossible) to execute different instructions if they are in the same group.
The way you mentioned is more suitable for many-core accelerators or processors like Intel Xeon Phi or AMD ThreadRipper, which contains a truly full-functional cores. Or even on FPGAs for many decoding IP to parse the frames.

I hope this could help.

Cheers,
Haolei (Saki) Ye

**Comment by tangram67** [comment]
Hi Haolei.

Yes, I think my approach is the "old school" way of decoding files ;-)

I fully understand the idea behind all CUDA cores accessing the same source and destination buffers in the same way.
The reason why I asked is, that I want to use your decoder in a music player I have written (see https://github.com/tangram67/RMP or https://github.com/tangram67/RMP/blob/master/src/inc/flac.cpp). The player is buffering whole files to memory and ALSA playback starts on the same mapped memory regions when a certain "watermark" is reached. So there is no concurrency between playback and decoder. I'm using an array of buffers, let's say 32 buffers with 128 MB of PCM data each. Usually one decoded file is stored in one buffer, if the buffer is too small to take one file, the next buffer is used for the upcoming data of the same file, and so on...

So for my usecase it would be great to have some kind of callback from the CUDA decoder where to store the destination data for a size and position/offset given by the CUDA decoder. I'm not sure if that is technically possible, because that means somehow call code in the calling process. What do you think about such an approach?

Thanks,
Dirk.

**Comment by Harinlen** [comment]
Hi Dirk,

Thanks for your interest with this project. Your approach is technically possible, however, I suggest you to scan the FLAC data first, then use multi-threads to decode the frames in CPU. Audio decoding is actually not suitable for GPU frameworks. From our test, CUDA decoder could provide about 5 times better times on GTX1080 compared to i7 6770K single core performance. The time of data transferring (from your memory to graphics memory) and branch prediction punishment reduced core number advantages (GTX1080 has 2560 CUDA cores, while 6770K only has 4 cores). If you really required such kind of performance, directly decode them in CPU is a much better choice.

I hope this could help you in your awesome player.

Cheers,
Haolei

**Comment by tangram67** [comment]
I think you're right. The GPU performance compared to (at least a single) CPU is not that much compared to the higher complexity when moving to GPU decoding. I will pick up your suggestion and see if the decoding process can be run on several CPU cores.

And thanks for your kind words about my music player!

Greetings,
Dirk.
